[package]
name = "lifeblox/replicaservice"
description = "Roblox state replication system, ported to wally with changes for framework."
authors = ["life-media","MadStudioRoblox"]
version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]